### ISSUE TITLE
UnitTest: "getDatabaseAwareTestCases" hides unnamed testCases

### ISSUE THREAD

**Issue by glady** [sigma-z/Dive#10]
introduced: 
 - date; 2014-05-02
 - commit: https://github.com/sigma-z/Dive/commit/94596d749a8f76cd7968bf3cde5c8a1abec218c9

fixed:
 - date: 2015-04-23
 - commit: https://github.com/sigma-z/Dive/commit/7d18b9187acb48012a9f1d432e2edea41e5604ec

Currently because of this issue-fix there are some changes on Platform-Datatypes that cause error within tests:
- MySql -> boolean is not expected to be mapped to tinyint
- SQLite -> timestamp is expected to be mapped to integer - but is implemented to return datetime now

When tests are fixed, this issue is done.

**Comment by glady** [comment]
@sigma-z Please review! Close issue, if DataType-Mapping is correct now. I only set failing tests expected values to current definition within definition of mapping-Classes!

**Comment by sigma-z** [comment]
Review: OK
